//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.OrderB = new HashSet<OrderB>();
            this.ServiceandOrder = new HashSet<ServiceandOrder>();
        }
    
        public int ID { get; set; }
        public string Sname { get; set; }
        public string Name { get; set; }
        public string Fname { get; set; }
        public int SeriosPassport { get; set; }
        public int NumberPassport { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int Index { get; set; }
        public int City_id { get; set; }
        public int Street_id { get; set; }
        public int House { get; set; }
        public int Flat { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    
        public virtual City City { get; set; }
        public virtual Street Street { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderB> OrderB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceandOrder> ServiceandOrder { get; set; }
    }
}
