//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientManager
    {
        public string Sname { get; set; }
        public string Name { get; set; }
        public string Fname { get; set; }
        public int SeriosPassport { get; set; }
        public int NumberPassport { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public int Flat { get; set; }
        public int House { get; set; }
    }
}
