//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryAdminWindow
    {
        public Nullable<System.DateTime> Дата { get; set; }
        public string Вход { get; set; }
        public string FIO { get; set; }
        public string LoginPassword { get; set; }
        public string Login { get; set; }
    }
}
