//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceandOrder
    {
        public string Code_Order { get; set; }
        public System.DateTime Date { get; set; }
        public int Code_client { get; set; }
        public Nullable<int> Service { get; set; }
        public int Order { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual OrderB OrderB { get; set; }
        public virtual Service Service1 { get; set; }
    }
}
